<?php

namespace AppBundle\Repository;

/**
 * AukcjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AukcjeRepository extends \Doctrine\ORM\EntityRepository
{
}
